CREATE TABLE store (
	store_id int4 NOT NULL,
	currency_code varchar(255) NULL,
	identifier varchar(255) NULL,
	markfordelete int4 NULL,
	store_name varchar(255) NULL,
	CONSTRAINT store_pkey PRIMARY KEY (store_id),
	CONSTRAINT uk_5x5ucpcvg3pw2576vdj19b4s7 UNIQUE (identifier)
);


CREATE TABLE category (
	category_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	identifier varchar(255) NULL,
	image_url varchar(255) NULL,
	mark_for_delete int4 NOT NULL,
	"name" varchar(255) NULL,
	top_category bool NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (category_id),
	CONSTRAINT uk_kqc3fdbcqtogvw8afgwq9cu5i UNIQUE (identifier)
);





CREATE TABLE catentry (
	catentry_id int4 NOT NULL,
	base_price numeric(19,2) NULL,
	exclusive_price numeric(19,2) NULL,
	extra_price numeric(19,2) NULL,
	identifier varchar(255) NULL,
	images varchar(5000) NULL,
	long_desc varchar(255) NULL,
	markfordelete int4 NULL,
	offer_price numeric(19,2) NULL,
	prod_qty int4 NOT NULL,
	product_id int4 NULL,
	product_name varchar(255) NULL,
	short_desc varchar(255) NULL,
	sort_order int4 NOT NULL,
	up_product_name varchar(255) NULL,
	CONSTRAINT catentry_pkey PRIMARY KEY (catentry_id),
	CONSTRAINT uk_fxuda2s2knc3rtqh7bimpg8ay UNIQUE (identifier)
);





CREATE TABLE catgrprel (
	id int4 NOT NULL,
	category_id_child int4 NULL,
	category_id_parent int4 NULL,
	relation_type varchar(255) NULL,
	CONSTRAINT catgrprel_pkey PRIMARY KEY (id)
);











CREATE TABLE catgpenrel (
	catentry_id int4 NOT NULL,
	category_id int4 NOT NULL,
	CONSTRAINT catgpenrel_pkey PRIMARY KEY (catentry_id, category_id),
	CONSTRAINT fkcr44816lv1q9wi6q6o98mswya FOREIGN KEY (catentry_id) REFERENCES catentry(catentry_id),
	CONSTRAINT fko4v4txq3fjjl1g8bjybg3fj8t FOREIGN KEY (category_id) REFERENCES category(category_id)
);





CREATE TABLE storecatentry (
	catentry_id int4 NOT NULL,
	store_id int4 NOT NULL,
	CONSTRAINT storecatentry_pkey PRIMARY KEY (catentry_id, store_id),
	CONSTRAINT fke4asxeetnxadqp2b95gc3yegg FOREIGN KEY (store_id) REFERENCES store(store_id),
	CONSTRAINT fknktfs6npqyg1wsh0f2tncki1s FOREIGN KEY (catentry_id) REFERENCES catentry(catentry_id)
);

insert into store values (1, 'USD', 'estore',0,'estore');

INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(1, 'Men Performance Essential Drop Cut T-Shirts', 'string', 0, 'Men Performance Essential Drop Cut T-Shirts', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(2, 'Men Performance Essential T-Shirts', NULL, 0, 'Men Performance Essential T-Shirts', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(3, 'Men Running Shorts', NULL, 0, 'Men Running Shorts', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(4, 'Vests', NULL, 0, 'Vests', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(5, 'Men Performance Vests', NULL, 0, 'Men Performance Vests', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(6, 'Men Enduro Joggers', NULL, 0, 'Men Enduro Joggers', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(7, 'Men Compression T-Shirts', NULL, 0, 'Men Compression T-Shirts', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(8, 'Men Base Layer', NULL, 0, 'Men Base Layer', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(9, 'Jerseys', NULL, 0, 'Jerseys', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(10, 'Men Knit Jackets', NULL, 0, 'Men Knit Jackets', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(11, 'Performance Shorts', NULL, 0, 'Performance Shorts', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(12, 'Performance Jerseys', NULL, 0, 'Performance Jerseys', false);
INSERT INTO category (category_id, identifier, image_url, mark_for_delete, "name", top_category) VALUES(13, 'Tank Tops', NULL, 0, 'Tank Tops', false);
